### ISSUE TITLE
[protobuf 4 incompatible bug] ClassNotFoundException: com.google.protobuf.GeneratedMessageV3

### ISSUE THREAD

**Issue by peterweb2005** [googleapis/java-datastore#1394]
as version 4 vs 3

**Comment by kolea2** [comment]
Hi @peterweb2005, can you provide some more info here to help us diagnose? Here's our bug template to help you get started:

----------------------------------------------------------------
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-datastore/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4.  version(s):

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```java
// example
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below


Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by peterweb2005** [comment]
@kolea2 library depends on protobuf 3, but newest protobuf is 4,
there no GeneratedMessageV3

**Comment by suztomo** [comment]
@peterweb2005 Is this (unable to use protobuf-java version 4) causing any problem to you right now?

**Comment by peterweb2005** [comment]
just want to know when fixed

**Comment by suztomo** [comment]
OK. Thanks. I don't have answer right now.

**Comment by peterweb2005** [comment]
seems fixed
