### ISSUE TITLE
Customize gcloudCommand of LocalDatastoreHelper

### ISSUE THREAD

**Issue by vtnlinh95** [googleapis/java-datastore#19]
I am using Spring Cloud GCP. It has the auto-configuration to start datastore emulator when starting the app engine devserver. However, when I read through the set up of LocalDatastoreHelper, I could see that the gcloudCommand is hard-coded. Are there any ways that I can customize the options of gcloudCommand ?

```
    List<String> gcloudCommand = new ArrayList<>(Arrays.asList(GCLOUD_CMD_TEXT.split(" ")));
    gcloudCommand.add(GCLOUD_CMD_PORT_FLAG + "localhost:" + getPort());
    gcloudCommand.add(CONSISTENCY_FLAG + consistency);
    gcloudCommand.add("--no-store-on-disk");
    GcloudEmulatorRunner gcloudRunner =
        new GcloudEmulatorRunner(gcloudCommand, VERSION_PREFIX, MIN_VERSION);
    if (gcdPath != null) {
      gcloudCommand.add("--data-dir=" + gcdPath.toString());
    }
```

I want to remove the option `--not-store-on-disk` and would like to change the `--data-dir` to my local folder.
Moreover, could you help me to find the location of the current data-dir. I do not know where it is.
Thanks

**Comment by aschroder** [comment]
I'd like to add my support to this request :) 

Couple of ideas to achieve it: 
- make the LocalDatastoreHelper handle configurable start up params
- make it subclass-able so that subclasses can manipulate the `emulatorRunners`

If you're open to either change, I'm happy to PR it.

**Comment by BenWhitehead** [comment]
Hi @aschroder Thanks for volunteering to help out!

I think adding the ability to provide some more config parameters would probably be a better path in the long run. I don't think we want to go the route of subclassing for config changes since that creates challenges down the road.

I'm envisioning the following changes here:
1. Create a new class `com.google.cloud.datastore.testing.LocalDatastoreHelper.Builder`
2. Add each of the existing parameters to the new builder
3. Add new parameters for data-dir etc to the builder
4. Move the current default values from the [constructor](https://github.com/googleapis/java-datastore/blob/ce0fd116dbc5de69ae4526d95cd8014eaf2da1a0/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java#L81) into the new builder
5. Refactor existing [`create`](https://github.com/googleapis/java-datastore/blob/ce0fd116dbc5de69ae4526d95cd8014eaf2da1a0/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java#L164) methods to use the new builder
6. Add a new `builder()` factory method to `LocalDatastoreHelper`

This should keep compatibility of the existing API, and keep the existing behavior, while exposing the builder for those folks that want more fine-grained control.

What do you think? Does this sound like something you have time to tackle?
