### ISSUE TITLE
Google DataStore iterating over QueryResults is too slow

### ISSUE THREAD

**Issue by rurao** [googleapis/java-datastore#294]
I have around 20,000 entities stored in google datastore. The datastore project is in us-central and I am querying from my laptop in California. When I query for all entities and iterate over the results it is taking about 30 seconds. This seems too slow. Am I doing something wrong?

Here is the sample scala code. I am using google-cloud-datastore version 1.105.3 and scala 2.12

```scala
    import com.google.cloud.datastore._

    println(LocalDateTime.now()) //-----> 2020-12-20T10:36:24.242
    val q = Query.newEntityQueryBuilder().setKind("Test").build()
    val datastore = DatastoreOptions.newBuilder().setProjectId("my-project-id").build().getService
    val es = datastore.run(q,  Seq.empty[ReadOption]: _*)
    
    println(LocalDateTime.now()) //---> 2020-12-20T10:36:24.881
    
    while (es.hasNext) {
          val e = es.next()      // Just iterating over the results.
        }
    
    println(LocalDateTime.now()) //----> 2020-12-20T10:36:53.870 (~29 seconds later)
```

The query run returns almost immediately but it seems like the getting the results is taking time. 

Also, when I try to get the count of the entities using the suggested method of setting the offset to `Int.MaxValue` I always get `getSkippedResults` as 1000. I verified that `es.hasNext` is false as well.

**Comment by BenWhitehead** [comment]
Hi @rurao,

The iterator [returned](https://github.com/googleapis/java-datastore/blob/master/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java#L89-L103) by `datastore.run` in your code sample is actually a lazy iterator which handles the result pagination for the query. Datastore caps each page to no more than 300 entities, so under the hood to process the 20,000 entities the iterator is actually sending and processing at least 67 requests and responses in sequence.

The call to datastore.run immediately returns an iterator which won't send the first request until `hasNext` or `next` are called on it.

**Comment by rurao** [comment]
@BenWhitehead - Thanks for the clarification! 
Figured that there is some batching going on in the background. In that case 
a) Is there any way to increase the page size? 

b) I wanted to get the total count of the results and then try to spawn some threads to get results in parallel. But when I try to get the count of the entities using the suggested method of setting the offset to `Int.MaxValue` I always get `getSkippedResults` as 1000. I verified that `es.hasNext` is `false` as well.

**Comment by BenWhitehead** [comment]
There is no way to increase the page size as it is enforced by the API layer.

If you have the ability to run multiple requests in parallel you may be able to leverage scatter queries.

The idea with a scatter query is that you can essentially submit a query and ask that it be broken up into a number of chunks, the result will be a list of keys which can then be used as upper and lower bounds on each of the queries. Here are some details about how you scatter queries work/can be used and where you can learn more information.

Based on my understanding, using an offset still requires the backend to scan the full index for the query. My guess, is the backend is not performing the full scan which can be very very costly and instead is essentially telling you there are at least 1000 entities.

## Scatter Queries in Datastore
Entities stored in Datastore have a metadata property `__scatter__` and a corresponding single-field-index that is automatically built.

### How it works
Conceptually you can think of the `__scatter__` index as having a naturally ascending sort order roughly similar to an n-ary tree in level order traversal. i.e. The first value is near the middle of the key space, as you move on from first you start to get keys less than and keys greater than the parent layers key. 

To access the `__scatter__` index, we issue a key only query which is able to fetch a set of keys that start spreading out from the middle of the key space up to the `limit` specified. Once the set of keys has been retrieved they can be sorted and then paired off to create cursor ranges to be added to any query.

Imagine I have an Entity Type `Book`, where each Book has a few properties. As my Books are inserted into Datastore, once every N number of entities have been inserted the key will be added to the `__scatter__` index.

A gql query representing how to access the scatter index is as follows:

`select __key__ from Book order by __scatter__ limit x`

Here `x` represents how many values you want. So, if you wanted to roughly partition the key space into 5 buckets, you would want to set the limit to 4 (since we want to query 5 ranges, we can implicitly define the 5th range by not defining an end to it, I'll illustrate with an example below).

#### A detailed breakdown
##### Key Ranges
My Book entities are keyed using hex strings of 32-bit integers representing the hash of the entity stored. Therefore my keyspace is 0x0000000 - 0xFFFFFFFF. When querying against the `__scatter__` index I am able to get the following ranges (after sorting and pairing off).

The following ranges are a result of running the above gql query where x is set to the limit number
###### Limit 1
```
ranges = [
             x <= 695DD481  (1,767,756,929)
  695DD481 < x              (2,527,210,366)
]
```
###### Limit 2
```
ranges = [
             x <= 57ECA083  (1,475,125,379)
  57ECA083 < x <= 695DD481  (  292,631,550)
  695DD481 < x              (2,527,210,366)
]
```
###### Limit 4
```
ranges = [
             x <= 48C9D796  (1,221,187,478)
  48C9D796 < x <= 57ECA083  (  253,937,901)
  57ECA083 < x <= 695DD481  (  292,631,550)
  695DD481 < x <= 95E4309D  (  747,002,908)
  95E4309D < x              (1,780,207,458)
]
```
###### Limit 16
```
ranges = [
             x <= 1C58CB98  (  475,581,336)
  1C58CB98 < x <= 20EC6100  (   76,780,904)
  20EC6100 < x <= 243F8CCA  (   55,782,346)
  243F8CCA < x <= 265EA6BB  (   35,592,689)
  265EA6BB < x <= 48C9D796  (  577,450,203)
  48C9D796 < x <= 57ECA083  (  253,937,901)
  57ECA083 < x <= 61953108  (  162,041,989)
  61953108 < x <= 695DD481  (  130,589,561)
  695DD481 < x <= 8CDE5960  (  595,625,183)
  8CDE5960 < x <= 95E4309D  (  151,377,725)
  95E4309D < x <= 9BC50E88  (   98,622,955)
  9BC50E88 < x <= A8166B7D  (  206,658,805)
  A8166B7D < x <= E50B200E  (1,022,669,969)
  E50B200E < x <= E7D17F89  (   46,555,003)
  E7D17F89 < x <= E9A5EA9E  (   30,698,261)
  E9A5EA9E < x <= F969A2BD  (  264,484,895)
  F969A2BD < x              (  110,517,570)
]
```

### How to leverage
The scatter queries to provide us with "ranges" of cursor values, which can then be leveraged in a series of queries to allow parallel fetching and execution of actual entity retrieval.

#### Proposed RPC Plan
1. queryScatter(numRanges)
   * keys are returned out of order, so we unfortunately can't short circuit this step to start dispatching the sub-queries quicker.
2. sort returned keys using existing key sorting
3. create `CursorRange`s for each 
   * (null, sortedKeys[0])
   * (sortedKeys[0], sortedKeys[1])
   * ...
   * (sortedKeys[N], null)
4. for each cursor_range in cursor_ranges, create a new key query based on original query and setting `startCursor` and/or `endCursor`, dispatch each new query asynchronously
5. wait for all queries to finish from step 4
6. count the number of keys returned from each of the result sets from 5

### Resources / Usages in OSS code
1. Java [com.google.datastore.v1.client.DatastoreHelper#getQuerySplitter.getSplits()](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/java/datastore/src/main/java/com/google/datastore/v1/client/QuerySplitterImpl.java#L60)
2. [Datastore Metadata Queries](https://cloud.google.com/datastore/docs/concepts/metadataqueries)
3. https://cloud.google.com/datastore/docs/reference/data/rpc/google.datastore.v1#google.datastore.v1.QueryResultBatch
4. Apache Beam Datastore Connector
   * https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java#L310

**Comment by rurao** [comment]
@BenWhitehead - Will check it out. Thanks!

**Comment by ppawel** [comment]
Why has this issue been closed without any conclusion? The query splitting functionality would be very useful addition to the client library. It is already implemented in the "other" Google Java Datastore client library (see `com.google.datastore.v1.client.QuerySplitter`) so it's a bit confusing why this one does not support it as well.

Especially that Spring GCP uses this library and without the query splitting support here, it is very hard to integrate it into Spring which means that all the nice Spring Data repository stuff is stuck with the slow cursor-based approach.

**Comment by duyleekun** [comment]
@BenWhitehead This is a good read and very enlightening.

I checked [Datastore Metadata Queries](https://cloud.google.com/datastore/docs/concepts/metadataqueries) and there's no mentioned of `__scatter__` field anywhere. Are you giving this document for understanding `metadata` concept or it does write about scatter concept?
